version: "3"
services:
  worker:
    image: worker
    depends_on:
      - rabbit
      - redis
      # worker must wait for both
      # rabbit & redis to comp. start
    command: ['./worker-wait.sh']
  rabbit:
    image: rabbitmq:latest
    expose:
      - "5672"
  redis:
    image: redis:latest
    expose:
      - "6379"
